### ISSUE TITLE
Why can it be predicted whether the ego-vehicle will collide with other traffic participants?

### ISSUE THREAD

**Issue by fdsaggaw** [Cogito2012/UString#11]
Thanks for your work.
In your work,you use the bounding box as the node of the graph structure,but the ego-vehicle does not appear in the video frame.Why can it be predicted whether the ego-vehicle will collide with other traffic participants?
Looking forward to your reply.

**Comment by Cogito2012** [comment]
@fdsaggaw This is a good question. In general, traffic accidents could happen on either the viewed objects or the ego-centric vehicle. For ego-centric accidents, they can be predicted by the temporal dynamics manifested in the visual scene, e.g., the frontal viewed vehicles/pedestrians becoming visually larger indicates high ego-centric accident risk in the near future.  Therefore, we assume that they viewed objects still can be used to model the scene dynamic for ego-centric accident anticipation. 

Besides, we also notice that in some video samples, only the ego-centric vehicle involved in a traffic accident, e.g., the ego-vehicle runs out of its driving lane and finally rollover due to slippery road conditions. For this case, we admit that graph network may not help a lot and it could be a promising future research direction.

**Comment by fdsaggaw** [comment]
Thank you for your answer.
In addition，the frame-level and all object-level features are concatenated to represent  the node of the graph structur.What is the effect of merging the frame-level feature?

**Comment by Cogito2012** [comment]
@fdsaggaw By incorporating the frame-level feature, extra information about the background of the traffic scene can be introduced into the model. In this work, we follow the same motivation as the baseline work (Chan et al, ACCV'16) where the full-frame feature also shows a bit of performance gain.
