### ISSUE TITLE
CarCrashDataset unzip error

### ISSUE THREAD

**Issue by Giuse1** [Cogito2012/UString#2]
Hello.
When I try to unzip files of vgg16_features.zip from CarCrashDataset, after extracting some .npz file I get the following error  "001848.npz error:  zipfile read error". 
How can I fix it?

**Comment by Cogito2012** [comment]
> Hello.
> When I try to unzip files of vgg16_features.zip from CarCrashDataset, after extracting some .npz file I get the following error "001848.npz error: zipfile read error".
> How can I fix it?

Thanks for your interest in this dataset.  It seems that your downloaded file `vgg16_features.zip` is corrupted.  You may follow the possible solutions [here ](https://askubuntu.com/questions/960552/cant-unzip-zip-file-in-terminal-because-of-a-single-corrupted-file)to repair the zip file. I've tested again to unzip the `vgg16_features.zip` in my local machine, and everything is fine, so if you cannot repair it, I suggest you to download it again.
